"""One-off: append sources on how partial implementations combine across partners, and on deepening.
Run once from the project root: .venv/bin/python docs/sciti2/citations/append_2026-09-19_combination.py"""
import csv
from pathlib import Path

CSV = Path("docs/sciti2/citations/citations.csv")
DOC = "docs/sciti2/multi-party-combination-proposal.md"
VIS = "proposal: concave depth g(d)=d^0.5 for visibility; additive in partner share (no value changed yet)"
TRC = "proposal: two-tier traceability, w*min(d_i,d_j) + (1-w)*mean, w~0.5; degraded tier without a live partner (no value changed yet)"
DEEP = "proposal: partial implementations deepen ~2%/month after month 6 (4% with a live partner); 25-40% never deepen (judgment)"
# technology, topic, parameter, citation, year, url, finding, flag, read_level, role, informs_value
ROWS = [
 ("control_tower", "combination shape", "visibility (depth transform)", "Gavirneni, Kapuscinski & Tayur (1999), Value of information in capacitated supply chains, Management Science 45(1):16-24", "1999", "https://pubsonline.informs.org/doi/10.1287/mnsc.45.1.16", "None -> partial information saves 10-90% of supplier cost (avg ~50%); partial -> full adds only 1-35%. The first increment of depth captures most of the value (strongly concave). Numbers read in Sahin & Robinson (2002)", "PR", "page or full text (via Sahin & Robinson 2002 review)", "MID anchor: partial depth captures ~60-80% of full value", VIS),
 ("control_tower", "combination shape", "visibility (depth transform)", "Sahin & Robinson (2002), Flow coordination and information sharing in supply chains: review, implications, and directions for future research, Decision Sciences 33(4)", "2002", "https://bauer.uh.edu/doctoral/scm/docs/Sahin-3.pdf", "Review giving the numeric results of Gavirneni et al. 1999, Cachon & Fisher 2000, Chen 1998, and Lee, So & Tang 2000", "PR", "page or full text", "source of several effect sizes", VIS),
 ("control_tower", "combination shape", "visibility (depth transform)", "Chen (1998), Echelon reorder points, installation reorder points, and the value of centralized demand information, Management Science 44(12)", "1998", "", "Centralized demand information is worth 1.75% of cost on average, 9% at most", "PR", "page or full text (via Sahin & Robinson 2002 review)", "LOW anchor (deep-sharing increment is small)", VIS),
 ("control_tower", "combination shape", "visibility (partner share)", "Dominguez, Cannella, Ponte & Framinan (2022), Information sharing in decentralised supply chains with partial collaboration, Flexible Services and Manufacturing Journal 34:263-292", "2022", "https://link.springer.com/article/10.1007/s10696-021-09405-y", "Four-echelon chain, 7 partial-sharing structures: bullwhip falls as the number of sharing echelons grows, regardless of position; no weakest-link collapse when one echelon abstains; each echelon's own result depends most on downstream collaboration", "PR", "snippet/abstract", "shape: monotone, additive-like in partners; supports the model's use of downstream share", VIS),
 ("control_tower", "combination shape", "visibility (partner share)", "Dominguez, Cannella, Barbosa-Povoa & Framinan (2018), Information sharing in supply chains with heterogeneous retailers, Omega 79:116-132", "2018", "https://ideas.repec.org/a/eee/jomega/v79y2018icp116-132.html", "Bullwhip reduction ~20-25% with 2 retailers sharing vs ~40-50% with all (4 retailers, from memory): roughly linear in the share of partners live; gains depend on which retailers share", "PR", "snippet/abstract", "shape: ~linear in partner share", VIS),
 ("control_tower", "combination shape", "visibility (partner share)", "Dominguez, Cannella, Barbosa-Povoa & Framinan (2018), OVAP: a strategy to implement partial information sharing among supply chain retailers, Transportation Research Part E 110:122-136", "2018", "https://ideas.repec.org/a/eee/transe/v110y2018icp122-136.html", "Enrolling high-order-variance retailers first beats the worst ordering by 27.2% on bullwhip and 7.8% on inventory: concave when partners are enrolled by importance", "PR", "snippet/abstract", "shape: concave under targeting", VIS),
 ("control_tower", "combination shape", "visibility (partner share)", "Raghunathan (2003), Impact of demand correlation on the value of and incentives for information sharing in a supply chain, EJOR 146(3)", "2003", "https://www.sciencedirect.com/science/article/abs/pii/S037722170200365X", "Manufacturer's marginal surplus per added sharing retailer declines when demands are correlated: concave in number of partners when information overlaps", "PR", "snippet/abstract", "shape: concave with correlated demand", VIS),
 ("control_tower", "combination shape", "visibility (partner share)", "Ganesh, Raghunathan & Rajendran (2014), The value of information sharing in a multi-product, multi-level supply chain, Decision Support Systems 58:79-94", "2014", "https://www.sciencedirect.com/science/article/abs/pii/S0167923613000225", "Partial (downstream-only or upstream-only) sharing has positive but smaller value than chain-wide sharing; value accrues mostly upstream (upstream detail from memory)", "PR", "snippet/abstract", "shape: partial sharing keeps positive value", VIS),
 ("control_tower", "combination shape", "visibility", "Chatfield, Kim, Harrison & Hayya (2004), The bullwhip effect: impact of stochastic lead time, information quality, and information sharing, POM 13(4):340-353", "2004", "https://journals.sagepub.com/doi/abs/10.1111/j.1937-5956.2004.tb00222.x", "Information sharing cuts variance amplification by nearly 50% at the factory; information quality is highly significant", "PR", "snippet/abstract", "context", VIS),
 ("control_tower", "combination shape", "visibility", "Costantino, Di Gravio, Shaban & Tronci (2014, 2015), Computers & Industrial Engineering", "2015", "https://www.sciencedirect.com/science/article/abs/pii/S0360835215000431", "Four-echelon simulations: information sharing is the most significant factor; benefits rise with the number of echelons sharing (monotonicity from memory)", "PR", "snippet/abstract", "context", VIS),
 ("control_tower", "combination shape", "visibility", "Ojha, Sahin, Shockley & Sridharan (2019), Is there a performance tradeoff in managing order fulfillment and the bullwhip effect?, IJPE 208:529-543", "2019", "https://www.sciencedirect.com/science/article/abs/pii/S0925527318304997", "Without sharing, the information type that gives the best fill rate gives the worst bullwhip; sharing removes the tradeoff", "PR", "snippet/abstract", "context", VIS),
 ("control_tower", "combination shape", "visibility (data-quality floor)", "Kwak & Gavirneni (2015), Impact of information errors on supply chain performance, EJOR; Cannella, Dominguez, Framinan & Ponte (2018), Demand sharing inaccuracies in supply chains, Complexity", "2018", "https://onlinelibrary.wiley.com/doi/10.1155/2018/1092716", "Shared data has no value (or does harm) once its error variance reaches the demand variance: a data-quality floor exists", "PR", "snippet/abstract", "optional floor on very shallow implementations", VIS),
 ("rfid", "effect size", "record_error_sd", "DeHoratius & Raman (2008), Inventory record inaccuracy: an empirical analysis, Management Science", "2008", "", "65% of 369,567 inventory records at the retailer studied were inaccurate", "PR", "snippet/abstract", "baseline context", "0.2 kept (0.25 at stores)"),
 ("blockchain", "combination shape", "defect_mult (pair rule)", "HHS Office of Inspector General (2009), Traceability in the food supply chain, OEI-02-06-00210", "2009", "https://oig.hhs.gov/oei/reports/oei-02-06-00210.pdf", "Real trace-back of 40 products through 118 facilities: only 5 of 40 (12.5%) traced through every stage; 31 of 40 got only 'likely' facilities; 4 of 40 broke entirely at one facility; 59% of facilities lacked required records. With ~41% compliant nodes and 2-4 node chains a product rule predicts 7-17%: lot-precise tracing is weakest-link, with a coarse fallback tier (78%)", "GOV", "page or full text", "MID anchor: weakest-link tier plus degraded tier", TRC),
 ("blockchain", "combination shape", "defect_mult (pair rule)", "Bhatt et al. / IFT (2013), Pilot projects for improving product tracing along the food supply system, Journal of Food Science", "2013", "https://ift.onlinelibrary.wiley.com/doi/10.1111/1750-3841.12298", "All 14 mock tracebacks succeeded among pilot participants; trace-forwards ended wherever recipients were not participants (the majority): the chain breaks at non-participants", "IND/PR", "snippet/abstract", "supports the weakest-link tier", TRC),
 ("blockchain", "combination shape", "defect_mult (pair rule)", "Golan, Krissoff, Kuchler et al. (2004), Traceability in the U.S. food supply: economic theory and industry studies, USDA ERS AER-830", "2004", "https://www.ers.usda.gov/publications/pub-details?pubid=41632", "Traceability has breadth, depth, and precision; depth is how far back the unbroken chain extends, structurally a min or product over links", "GOV", "snippet/abstract", "structure", TRC),
 ("blockchain", "combination shape", "defect_mult (pair rule)", "Dupuy, Botta-Genoulaz & Guinet (2005), batch dispersion model; Dabbene, Gay & Tortia (2014), Traceability issues in food supply chain management", "2014", "", "Worst-case recall size is set by the coarsest batch granularity and mixing in the chain (min-like)", "PR", "memory", "structure (unverified)", TRC),
 ("blockchain", "combination shape", "defect_mult (pair rule)", "Baiman, Fischer & Rajan (2000), Information, contracting, and quality costs, Management Science 46(6); Kremer (1993), The O-ring theory of economic development, QJE", "2000", "https://pubsonline.informs.org/doi/10.1287/mnsc.46.6.776.11939", "Supplier prevention and buyer appraisal are partial substitutes in delivered quality (the buyer's inspection catches supplier defects), so quality across a pair is not purely multiplicative (O-ring) (Kremer from memory)", "PR", "snippet/abstract", "supports a benefit tier that survives one weak partner", TRC),
 ("rfid", "combination shape", "hub vs spoke benefit", "Hardgrave, Waller & Miller (2005/2008), RFID's impact on out of stocks (Walmart), working paper and MIS Quarterly Executive 7(4)", "2008", "https://rfid.auburn.edu/papers/documents/RFIDImpactOutOfStock.pdf", "Out-of-stocks fell 26% in 12 test stores (net ~16-21% vs controls) from case-level tags applied by suppliers doing the shallowest compliance: the hub's benefit needs partners live, not deep; slap-and-ship gives the supplier nothing", "PR/IND", "page or full text", "hub benefit ~ partner coverage; spoke benefit ~ own depth", TRC),
 ("control_tower", "combination shape", "hub vs spoke benefit", "Lee, Clark & Tam (1999), Can EDI benefit adopters?, Information Systems Research 10(2):186-195", "1999", "https://ideas.repec.org/a/inm/orisre/v10y1999i2p186-195.html", "31 grocery chains on Campbell's continuous replenishment: higher turns and fewer stockouts when EDI came with inter-firm process redesign; EDI alone gives little (latter from memory)", "PR", "snippet/abstract", "own depth drives own benefit", VIS),
 ("control_tower", "combination shape", "hub vs spoke benefit", "Mukhopadhyay, Kekre & Kalathur (1995), Business value of information technology: a study of electronic data interchange, MIS Quarterly 19(2):137-156", "1995", "https://misq.umn.edu/business-value-of-information-technology-a-study-of-electronic-data-interchange.html", "Chrysler: $220M a year saved; savings roughly linear in the share of supplier volume on EDI (linearity and ~$60-100 per vehicle from memory)", "PR", "snippet/abstract", "hub benefit ~ linear in partner coverage", VIS),
 ("control_tower", "combination shape", "hub vs spoke benefit", "Subramani (2004), How do suppliers benefit from information technology use in supply chain relationships?, MIS Quarterly 28(1):45-73", "2004", "https://aisel.aisnet.org/misq/vol28/iss1/5/", "131 suppliers on one retailer's system: supplier benefits are mediated by the supplier's own relationship-specific investments", "PR", "snippet/abstract", "spoke benefit ~ own depth", VIS),
 ("all", "deepening", "partial_fraction over time", "McAfee (2002), The impact of enterprise information technology adoption on operational performance, POM 11(1):33-53", "2002", "https://www.researchgate.net/publication/227948625", "Lead time and on-time delivery dipped at go-live, then improved along a learning curve; significantly better than before after several months", "PR", "snippet/abstract", "go-live dip then improvement", DEEP),
 ("all", "deepening", "partial_fraction over time", "Deloitte Consulting (1999), ERP's second wave; Markus & Tanis; Ross & Vitale (ERP stages)", "1999", "http://www.ctiforum.com/technology/CRM/wp01/download/erp2w.pdf", "Stabilisation period of 3-9 months (another source 4-12), then an 'onward and upward' phase in which most gains arrive", "IND", "snippet/abstract", "timing anchor: deepening starts after ~6 months", DEEP),
 ("all", "deepening", "partial_fraction over time", "Panorama Consulting (2013) ERP survey, as cited on a secondary slideshare page", "2013", "https://www.slideshare.net/slideshow/presentation-25482170/25482170", "60% got less than half the expected benefit; 27% less than a third; 11% none: a large share stay shallow", "VND", "snippet/abstract", "anchor for the never-deepen share (25-40%)", DEEP),
 ("all", "deepening", "partial_fraction over time", "Zhu, Kraemer & Xu (2006), The process of innovation assimilation by firms in different countries, Management Science 52(10); Liang, Saraf, Hu & Xue (2007), MIS Quarterly 31(1)", "2006", "https://escholarship.org/uc/item/61x575z7", "Assimilation runs initiation -> adoption -> routinisation (1,857 firms, 10 countries); adoption does not imply routinisation; top-management participation and pressure from dominant partners raise depth of use. No monthly rates", "PR", "snippet/abstract", "structure: depth grows after go-live, not for everyone", DEEP),
 ("all", "deepening", "partial_fraction over time", "Dyer & Hatch (2006), SMJ 27(8) (already C206): hub support and rate of improvement", "2006", "https://scholarsarchive.byu.edu/facpub/9798/", "Toyota's support roughly doubled suppliers' improvement rate (50% vs 26% defect cuts over six years); the gain did not transfer to other customers", "PR", "snippet/abstract", "hub support doubles the deepening rate; hub-specific", DEEP),
]


def main() -> None:
    with CSV.open() as f:
        existing = list(csv.DictReader(f))
    fields, n = list(existing[0].keys()), len(existing)
    assert not any(r["date_added"] == "2026-09-19d" for r in existing), "already appended"
    new = [dict(zip(fields, [f"C{i:03d}", "2026-09-19d", t, topic, p, c, y, u, fi, fl, rd, ro, inf, DOC]))
           for i, (t, topic, p, c, y, u, fi, fl, rd, ro, inf) in enumerate(ROWS, n + 1)]
    with CSV.open("a", newline="") as f:
        csv.DictWriter(f, fieldnames=fields).writerows(new)
    print(len(new), "rows appended; log now has", n + len(new))


if __name__ == "__main__":
    main()
