"""One-off: append the learning-effects sources (research of 2026-09-19).
Run once from the project root: .venv/bin/python docs/sciti2/citations/append_2026-09-19_learning.py"""
import csv
from pathlib import Path

CSV = Path("docs/sciti2/citations/citations.csv")
DOC = "docs/sciti2/learning-evidence.md"
RETRY = "retry_failure_odds 0.75 / 0.60 (LOW 0.90/0.85, HIGH 0.55/0.40); magnitude is judgment"
OWN = "own_success_failure_odds 0.87, floor 0.50 (LOW 0.95/0.75, HIGH 0.80/0.33)"
PART = "partner_success_failure_odds 0.88, floor 0.60 (LOW 0.95/0.80, HIGH 0.78/0.45); direct partners only"
DEP = "experience depreciation not modelled (3-year horizon); evidence 5-35%/yr"
TREND = "no global maturity trend modelled"
# parameter, citation, year, url, finding, flag, read_level, role, informs_value
ROWS = [
 ("retry_failure_odds", "Madsen & Desai (2010), Failing to learn? The effects of failure and success on organizational learning in the global orbital launch vehicle industry, AMJ 53(3):451-476", "2010", "https://journals.aom.org/doi/10.5465/amj.2010.51467631", "Prior failures cut future launch failure more than prior successes, and failure knowledge depreciates more slowly. A second-hand snippet gives 66%/yr depreciation for success vs 11%/yr for failure experience (unverified)", "PR", "snippet/abstract", "direction: organisations learn from failure", RETRY),
 ("retry_failure_odds", "KC, Staats & Gino (2013), Learning from my success and from others' failure: evidence from minimally invasive cardiac surgery, Management Science 59(11):2435-2449", "2013", "https://pubsonline.informs.org/doi/10.1287/mnsc.2013.1720", "71 surgeons, 6,500+ procedures: individuals learn more from their own successes than their own failures, and more from others' failures than others' successes. Coefficients not obtained", "PR", "snippet/abstract", "argues against a strong retry benefit", RETRY),
 ("retry_failure_odds", "Yin, Wang, Evans & Wang (2019), Quantifying the dynamics of failure across science, startups and security, Nature", "2019", "https://arxiv.org/abs/1903.07562", "Repeat attempters split into a group that improves and a group that does not; the two look alike at the start", "PR", "page or full text", "retry benefit varies widely across firms (not modelled)", RETRY),
 ("retry_failure_odds", "Eggers & Suh (2019), Experience and behavior: how negative feedback in new versus experienced domains affects firm action and subsequent performance, AMJ", "2019", "https://journals.aom.org/doi/10.5465/amj.2017.0046", "Failure in an experienced domain triggers productive search; failure in a new domain tends to trigger retreat (retreat result from memory)", "PR", "snippet/abstract", "context: retry benefit larger for experienced firms", RETRY),
 ("retry_failure_odds", "Haunschild & Sullivan (2002), Learning from complexity: effects of prior accidents and incidents on airlines' learning, ASQ 47(4):609-643", "2002", "https://papers.ssrn.com/sol3/papers.cfm?abstract_id=1004422", "Prior accidents reduce later accident rates, more so when causes are heterogeneous. No numbers retrieved", "PR", "snippet/abstract", "direction", RETRY),
 ("own_success_failure_odds", "Boone, Ganeshan & Hicks (2008), Learning and knowledge depreciation in professional services, Management Science 54(7):1231-1236", "2008", "https://ram-ganeshan.squarespace.com/s/learning-and-knowledge-depreciation-in-professional-services.pdf", "Progress ratio 0.88 (~12% gain per doubling of experience) on architecture/engineering projects; monthly knowledge retention 99.8%. Reviews retention elsewhere: auto assembly 67%/month, shipbuilding 75%, truck plant 81%, aircraft 96%, pizza franchises 47%", "PR", "page or full text", "scale anchor for learning; LOW anchor for depreciation", OWN + "; " + DEP),
 ("own_success_failure_odds", "Boh, Slaughter & Espinosa (2007), Learning from experience in software development: a multilevel analysis, Management Science 53(8):1315-1331", "2007", "", "Learning curves exist in software work; experience in the same or related systems matters most, unrelated experience least. No numeric rate retrieved", "PR", "snippet/abstract", "related experience counts more (not modelled: all technologies count equally)", OWN),
 ("own_success_failure_odds", "Huckman, Staats & Upton (2009), Team familiarity, role experience, and performance, Management Science 55(1):85-100", "2009", "https://pubsonline.informs.org/doi/10.1287/mnsc.1080.0921", "Team familiarity and role experience improve software project performance; generic tenure does not", "PR", "snippet/abstract", "context", OWN),
 ("own_success_failure_odds", "Gartner (30 Jun 2025), AI maturity survey, n=432", "2025", "https://www.gartner.com/en/newsroom/press-releases/2025-06-30-gartner-survey-finds-forty-five-percent-of-organizations-with-high-artificial-intelligence-maturity-keep-artificial-intelligence-projects-operational-for-at-least-three-years", "45% of high-maturity organisations keep AI projects in production 3+ years vs 20% of low-maturity: odds ratio ~3.3, i.e. failure odds x0.31 across the full maturity range", "IND", "snippet/abstract", "floor anchor (0.3-0.5)", OWN),
 ("own_success_failure_odds", "Standish Group CHAOS Report 2015 (team skill levels), via scrum.org", "2015", "https://www.scrum.org/resources/blog/key-lessons-standishs-2015-chaos-report", "Each team skill 'level up' raises the chance of success ~23% in relative terms; unskilled teams 60% challenged, 23% failed (unconfirmed: page fetch empty)", "IND", "snippet/abstract", "floor support (weak)", OWN),
 ("own_success_failure_odds", "BCG (2020), Flipping the odds of digital transformation success (press release)", "2020", "https://www.prnewswire.com/news-releases/companies-can-flip-the-odds-of-success-in-digital-transformations-from-30-to-80-301162310.html", "Success 30% rising to 80% with all six success factors in place (odds ratio ~9.3): an upper bound, self-reported, about management practices not experience", "IND", "page or full text", "upper bound", OWN),
 ("own_success_failure_odds", "McKinsey (2018), Unlocking success in digital transformations", "2018", "https://www.mckinsey.com/capabilities/quantumblack/our-insights/unlocking-success-in-digital-transformations", "Firms under 100 employees are 2.7x more likely to report transformation success than firms over 50,000. Runs against the small-firm penalty (self-reported; small scopes)", "IND", "snippet/abstract", "counter-evidence to small_firm_failure_odds", "small_firm_failure_odds 1.75 kept; flagged"),
 ("own_success_failure_odds", "Cohen & Levinthal (1990) absorptive capacity; Mayeh et al. (2016), JSS; ERP assimilation studies", "2016", "https://www.sciencedirect.com/science/article/abs/pii/S0164121216300565", "Mixed: absorptive capacity predicts ease of use, but one ERP assimilation study found prior IT knowledge unrelated (negative in private firms)", "PR", "snippet/abstract", "context (mixed)", OWN),
 ("own_success_failure_odds; partner_success_failure_odds", "Huang, Ceccagnoli, Forman & Wu (2022), IT knowledge spillovers, absorptive capacity, and productivity, ISR", "2022", "https://doi.org/10.1287/isre.2021.1091", "Peer IT knowledge spillovers (SAP forums) benefit only firms with prior related enterprise-software investment: own and vicarious learning are complements (not modelled: they multiply independently)", "PR", "snippet/abstract", "structure", OWN),
 ("partner_success_failure_odds", "Kim & Miner (2007), Vicarious learning from the failures and near-failures of others: evidence from the U.S. commercial banking industry, AMJ 50(3):687-714", "2007", "http://homepages.se.edu/cvonbergen/files/2013/01/Vicarious-Learning-from-the-failures-and-near-failures-or-others_Evidence-from-the-US-commercial-banking-industry.pdf", "A 1-SD rise in LOCAL peers' failure experience multiplies a bank's failure hazard by ~0.73 (near-failure experience ~0.30); out-of-state peers contribute nothing. Learning from others is strongly local", "PR", "page or full text", "MID anchor; direct partners only", PART),
 ("partner_success_failure_odds", "Dyer & Hatch (2006), Relation-specific capabilities and barriers to knowledge transfers, SMJ 27:701-719", "2006", "https://scholarsarchive.byu.edu/facpub/9798/", "The same US suppliers cut defects 50% for Toyota vs 26% for their largest US customer over 6 years (residual defects ~0.68x under an actively teaching hub)", "PR", "page or full text", "scale anchor; hub support (not modelled separately)", PART),
 ("partner_success_failure_odds", "Baum & Dahlin (2007), Aspiration performance and railroads' patterns of learning from train wrecks and crashes, Organization Science 18(3):368-385", "2007", "", "Both own and others' experience reduce accident costs; experience is discounted by age; US Class 1 railroads 1975-2001", "PR", "page or full text", "direction; depreciation exists", PART + "; " + DEP),
 ("partner_success_failure_odds", "Baum & Ingram (1998), Management Science 44:996-1016; Ingram & Baum (1997), ASQ 42:68-102 (Manhattan hotels)", "1998", "https://pubsonline.informs.org/doi/abs/10.1287/mnsc.44.7.996", "Industry experience before founding lowers failure; chain affiliation improves survival; local vs non-local matters. No coefficients retrieved", "PR", "snippet/abstract", "direction", PART),
 ("partner_success_failure_odds", "Dyer & Nobeoka (2000), Creating and managing a high-performance knowledge-sharing network: the Toyota case, SMJ 21:345-367", "2000", "", "Supplier associations, consulting teams, and learning groups spread know-how across Toyota's suppliers. No verified numbers", "PR", "memory", "context (hub teaching)", PART),
 ("partner_success_failure_odds", "Krause, Handfield & Tyler (2007), JOM 25:528-545; Modi & Mabert (2007), JOM 25:42-64", "2007", "https://onlinelibrary.wiley.com/doi/10.1016/j.jom.2006.05.007", "Direct involvement (site visits, training) drives supplier improvement; evaluation alone does not. Path coefficients, not odds", "PR", "snippet/abstract", "context: support matters more than pressure", PART),
 ("partner_success_failure_odds", "Iacovou, Benbasat & Dexter (1995), Electronic data interchange and small organizations, MISQ 19(4):465-485", "1995", "https://misq.umn.edu/electronic-data-interchange-and-small-organizations-adoption-and-impact-of-technology.html", "Hub pressure drives EDI adoption at small firms, but low readiness yields unintegrated, low-benefit EDI; hubs should give financial and technical help", "PR (cases)", "snippet/abstract", "hub pressure without support gives partial success", PART),
 ("partner_success_failure_odds", "Hart & Saunders (1998); Riggins & Mukhopadhyay (1994); Zhu, Kraemer et al. (2006), MISQ", "2006", "", "Coercive hub power raises adoption but narrows use; partner adoption raises adoption. No implementation-success odds", "PR", "memory", "context", PART),
 ("technology maturity trend", "Gartner (A. Litan) via CoinDesk (2021): blockchain projects reaching production 5% (2019) to 14% (2020)", "2021", "https://www.coindesk.com/markets/2021/05/25/consensus-2021-6-questions-for-gartners-avivah-litan", "Not-in-production odds fell ~0.32x in one year (confounded by survivor selection). 14% confirmed on the page; 5% from a snippet", "IND", "page or full text", "HIGH anchor for a maturity trend", TREND),
 ("technology maturity trend", "Accenture RFID in retail surveys via Loss Prevention Media", "2021", "https://losspreventionmedia.com/retail-rfid-adoption-in-north-america/", "2018 to 2020: pilot-only 48% to 8%, full adoption 28% to 47% (~0.65x per year on not-fully-adopted odds); n~50", "IND/VND", "snippet/abstract", "MID anchor for a maturity trend", TREND),
 ("technology maturity trend", "Gartner AI in Organizations surveys (press release 22 Aug 2022)", "2022", "https://www.gartner.com/en/newsroom/press-releases/2022-08-22-gartner-survey-reveals-80-percent-of-executives-think-automation-can-be-applied-to-any-business-decision", "AI pilots reaching production: 53% (2019) and 54% (2022): no population-level improvement in 3 years", "IND", "snippet/abstract", "LOW anchor: no trend", TREND),
 ("technology maturity trend", "Panorama Consulting ERP reports 2009-2012 (cost and duration)", "2012", "https://www.panorama-consulting.com/resource-center/erp-report-archives/", "$6.2M/18.4 mo (2009), $5.5M/14.3 (2010), $10.5M/16.0 (2011), $7.1M/17.8 (2012): noisy, no monotone decline", "VND", "snippet/abstract", "no trend", TREND),
 ("partner_success_failure_odds", "Wang & Chen (2006) and other ERP consultant-quality studies", "2006", "https://www.researchgate.net/publication/251911343", "Experienced consultants and integrators help in most critical-success-factor studies; at least one study finds no support. A vendor blog's '85% success with consultants' should be disregarded", "PR/VND", "snippet/abstract", "context (mixed)", PART),
 ("experience depreciation", "Argote, Beckman & Epple (1990), Management Science 36(2); Darr, Argote & Epple (1995), Management Science 41(11)", "1995", "https://ideas.repec.org/a/inm/ormnsc/v41y1995i11p1750-1762.html", "Knowledge depreciates rapidly in shipyards and pizza franchises; transfers across stores of the same franchisee, not across franchisees (transfer result from memory)", "PR", "snippet/abstract", "HIGH anchor for depreciation; locality of transfer", DEP),
]


def main() -> None:
    with CSV.open() as f:
        existing = list(csv.DictReader(f))
    fields, n = list(existing[0].keys()), len(existing)
    assert not any(r["date_added"] == "2026-09-19c" for r in existing), "already appended"
    new = [dict(zip(fields, [f"C{i:03d}", "2026-09-19c", "all", "learning", p, c, y, u, fi, fl, rd, ro, inf, DOC]))
           for i, (p, c, y, u, fi, fl, rd, ro, inf) in enumerate(ROWS, n + 1)]
    with CSV.open("a", newline="") as f:
        csv.DictWriter(f, fieldnames=fields).writerows(new)
    print(len(new), "rows appended; log now has", n + len(new))


if __name__ == "__main__":
    main()
