"""One-off: append the cost evidence and the helper-reported sources that never reached a write-up.
Run once from the project root: .venv/bin/python docs/sciti2/citations/append_2026-09-19_gaps.py"""
import csv
from pathlib import Path

CSV = Path("docs/sciti2/citations/citations.csv")
ET, FE, RI = ("docs/sciti2/evidence-table.md", "docs/sciti2/implementation-failure-evidence.md",
              "docs/sciti2/risk-intel-evidence-and-sensitivity.md")
COST = "placeholder costs kept in catalog v2; per the v2 sensitivity screen cost matters only for control tower, APS, and ML"
HELP = "research helper report (not in a write-up)"
# technology, topic, parameter, citation, year, url, finding, flag, read_level, role, informs_value, source_doc
ROWS = [
 # ---- cost evidence (evidence-table.md, prose) ----
 ("blockchain", "cost", "cost_one_time; cost_per_week", "ScienceSoft, Blockchain for supply chain (cost guide)", "", "https://www.scnsoft.com/blockchain/supply-chain", "Join an existing network $50-150k one-time; enterprise deployments $0.5-1M+", "VND", "not recorded", "cost range", COST, ET),
 ("blockchain", "cost", "cost_one_time", "Market Research Future, Blockchain supply chain market report", "", "https://www.marketresearchfuture.com/reports/blockchain-supply-chain-market-6702", "Mid-tier manufacturers retrofitting legacy systems routinely exceed $500k", "IND", "not recorded", "cost range", COST, ET),
 ("blockchain", "cost", "cost_per_week", "IBM Blockchain Platform pricing as cited in arXiv 2009.07834", "2020", "https://arxiv.org/pdf/2009.07834", "Small production setup ~$1.19/hr (~$10.4k/yr infrastructure); hosted node/platform $10-30k/yr", "VND", "not recorded", "cost range", COST, ET),
 ("blockchain", "cost", "cost_one_time", "Growth Shuttle, blockchain supply chain cost-saving case studies", "", "https://growthshuttle.com/blockchain-supply-chain-cost-saving-case-studies/", "SME ROI claimed in 18-24 months", "VND", "not recorded", "context", COST, ET),
 ("rfid", "cost", "cost_per_week", "rfidnews.co.uk, How to calculate RFID tag cost per unit at scale", "2026", "https://www.rfidnews.co.uk/2026/08/02/how-to-calculate-rfid-tag-cost-per-unit-at-scale/", "UHF labels $0.08-0.18 landed at 50k+ volume; $0.05-0.07 per inlay above 100k/yr", "VND", "not recorded", "cost range (tag spend dominates running cost)", COST + "; RFID running cost flagged as low for high-volume sites", ET),
 ("rfid", "cost", "cost_per_week", "JN RFID, passive UHF tag cost; KORONA POS, RFID tag cost", "", "https://jnrfid.com/passive-uhf-rfid-tag-cost-per-tag/ ; https://koronapos.com/blog/rfid-tag-cost/", "Tags ~$0.05 at >1M/yr; small site example: 10k tags $1,500 + reader $2,000 + install $7,500", "VND", "not recorded", "cost range", COST, ET),
 ("rfid", "cost", "cost_one_time", "rfidcard.com, RFID reader cost 2025; RMS Omega, the cost of an RFID system", "2025", "https://www.rfidcard.com/how-much-does-an-rfid-reader-cost-in-2025/ ; https://rmsomega.com/the-cost-of-an-rfid-system/", "Handheld $300-1,500; fixed reader + antennas $1,500-3,000 per portal", "VND", "not recorded", "cost range", COST, ET),
 ("rfid", "cost", "cost_one_time", "AssetPulse, RFID system cost; Vertical Systems, guide to RFID costs", "", "https://www.assetpulse.com/blog/rfid-system-cost ; https://vertsys.com/guide-to-rfid-costs/", "Enterprise $100k-1M+; per-store rollout $15-50k", "VND", "not recorded", "cost range", COST, ET),
 ("routing", "cost", "cost_one_time; cost_per_week", "Logistics Management (2014), State of TMS (ARC example)", "2014", "https://www.logisticsmgmt.com/article/supply_chain_technology_2014_state_of_tmscost_reductions_and_roi_continue_t", "$100M freight spend: $1-2M TMS investment, ~$8M/yr saved; TMS absorbs <10% of savings for ~60% of users", "IND (secondary)", "not recorded", "cost range (large shipper)", COST, ET),
 ("routing", "cost", "cost_per_week", "Shipwell, TMS software price", "", "https://www.shipwell.com/blog/tms-software-price", "SaaS TMS $50-500 per user per month; 5-year TCO often 2-3x licence", "VND", "not recorded", "cost range", COST, ET),
 ("routing", "cost", "cost_per_week", "SmartRoutes, route optimization software cost; Routific pricing", "", "https://smartroutes.io/blogs/route-optimization-software-cost/ ; https://www.routific.com/pricing", "SMB routing SaaS $25-89 per vehicle per month; Routific $150/month per 1,000 orders", "VND", "not recorded", "cost range (small fleet)", COST, ET),
 ("wh_robotics", "cost", "cost_one_time", "Kardex (2024), How much does AutoStore cost?", "2024", "https://www.kardex.com/en-us/blog/how-much-does-autostore-cost", "$1M small to $50M+; typical $3-6M; payback 2-3 years", "VND", "not recorded", "cost range (mid DC ~$4M)", COST, ET),
 ("wh_robotics", "cost", "cost_one_time; cost_per_week", "Layer3 Labs (2026), robotics-as-a-service; Robotomated (2026), warehouse robot cost guide", "2026", "https://www.layer3labs.io/robotics/robotics-as-a-service ; https://robotomated.com/learn/cost/warehouse-robot-cost-guide", "AMR $25-50k each or $2-4k per robot per month; GTP workstation $100-500k; 20k-SKU GTP $2-10M; payback 18-36 months", "VND (secondary)", "not recorded", "cost range", COST, ET),
 ("wh_robotics", "cost", "cost_one_time", "Logistics Navigators, Ocado technology and the economics of automated fulfilment", "", "https://www.logisticsnavigators.com/startup-corner/ocado-technology-and-the-economics-of-building-a-fully-automated-fulfillment-network", "Large CFC capex $200-300M; >600 UPH vs 60-80 manual", "ANEC", "not recorded", "cost range (hyperscale)", COST, ET),
 ("ml_forecast", "cost", "cost_one_time; cost_per_week", "Vendor/aggregator pricing pages for demand planning software (datup.ai, horizonsolutions.ai, shivlab.com, saasworthy)", "", "", "Enterprise $200-500k+/yr (large $0.5-2M/yr); mid-market $50-150k/yr; SMB $5-10k/yr; implementation 0.75-1.25x licence, $100-300k typical, 3-18 months", "VND", "snippet/abstract", "cost range", COST, ET),
 ("control_tower", "cost", "cost_one_time; cost_per_week", "pricingnow.com, control tower SaaS pricing (citing Gartner's 1-3x licence implementation rule)", "", "", "$10-25k/yr (1 user) to $200-500k+/yr (100 users); large platforms $0.5-2M/yr; implementation 1-3x first-year licence; enterprise programs $0.5-3M one-time", "VND", "page or full text", "cost range", COST, ET),
 ("control_tower", "cost", "cost_per_week", "FourKites/project44 pricing as reported by fareye.com, locus.sh, tradlinx", "", "", "FourKites enterprise from ~$75k/yr; project44 quote-only", "VND", "snippet/abstract", "cost range", COST, ET),
 ("aps", "cost", "cost_one_time; cost_per_week", "User Solutions, scheduling software cost guide", "", "https://usersolutions.com/blog/scheduling-software-cost", "Mid-market licence $50-200k one-time; services $30-100k; enterprise 2-3x licence; SaaS ~$4-20k/month", "IND (vendor-adjacent)", "not recorded", "cost range", COST, ET),
 ("aps", "cost", "cost_one_time", "ITQlick APS pricing; DecisionBrain (2026), APS software statistics", "2026", "https://www.itqlick.com/aps-advanced-planning-and-scheduling/pricing ; https://decisionbrain.com/aps-software-statistics-2026/", "Mid-size deployment + customisation can exceed $500k; 76% of large firms have some APS; VDMA: 47% face APS-ERP data inconsistencies", "IND (secondary)", "not recorded", "cost range", COST, ET),
 ("risk_intel", "cost", "cost_per_week", "GetApp, Resilinc pricing", "", "https://www.getapp.com/operations-management-software/a/resilinc/pricing/", "From ~$1,400 per feature per month (~$17k/yr per module); realistic starter $50-100k/yr", "VND", "not recorded", "cost range", COST + "; placeholder one-time cost flagged as high for a subscription", ET),
 ("risk_intel", "cost", "cost_per_week", "Vendr marketplace, Sphera (riskmethods) spend data", "", "https://www.vendr.com/marketplace/sphera", "Actual spend: SMB average $35,045/yr; enterprise average $261,060/yr (all Sphera products)", "IND (transaction data)", "not recorded", "cost range", COST, ET),
 ("risk_intel", "cost", "cost_per_week", "Interos on AWS Marketplace; Gartner Market Guide for Supplier Risk Management Solutions", "", "https://aws.amazon.com/marketplace/pp/prodview-h3m3irdg7bika ; https://www.gartner.com/en/documents/4996831", "Quote-based; enterprise platforms six to seven figures a year", "VND / IND (paywalled)", "snippet/abstract", "cost range", COST, ET),
 # ---- helper-reported sources that did not reach a write-up: effect sizes ----
 ("routing", "effect size", "ship_cost_mult; co2_mult", "Routing on-road heavy vehicles for alleviating GHG emissions (2021), Cleaner Logistics and Supply Chain (field case)", "2021", "https://www.sciencedirect.com/science/article/pii/S2666790821002858", "-4.8% distance, -14% time, -10.8% fuel vs existing routes (municipal heavy-vehicle fleet)", "PR (small)", "not recorded", "own-fleet CO2 anchor", "0.92 kept; co2 0.94 (was 0.90)", HELP),
 ("wh_robotics", "effect size", "handling_cost_per_unit x", "MHI / Deloitte Annual Industry Report 2025-2026", "2025", "https://www.mhi.org/annual-industry-reports", "45% plan to buy AGV/AS-RS/robotics within 3 years, 83% within 5; no effect sizes", "IND", "not recorded", "context (adoption)", "0.8 kept; -0.6 day (was -1.0)", HELP),
 ("blockchain", "effect size", "defect_mult", "Kezzler in Food Logistics, How strong traceability programs reduce risks of food recalls", "", "https://www.foodlogistics.com/safety-security/food-safety/article/22184349/kezzler-how-strong-traceability-programs-reduce-risks-of-food-recalls", "Average recall ~$10M; wide-net recalls cost 3-5x a targeted recall (unsourced averages; traceability in general)", "VND", "not recorded", "context (recall scope, not defects)", "0.82 (was 0.60); LOW 0.95-1.0, HIGH 0.65", HELP),
 ("blockchain", "effect size", "defect_mult", "McKinsey (2017), Blockchain technology for supply chains: a must or a maybe?", "2017", "https://www.mckinsey.com/capabilities/operations/our-insights/blockchain-technology-for-supply-chainsa-must-or-a-maybe", "Pilots have not proven the technology's unique value; traceability can be solved in other ways", "IND", "not recorded", "context (realisation risk)", "0.82 (was 0.60); LOW 0.95-1.0, HIGH 0.65", HELP),
 ("rfid", "effect size", "record_error_sd x", "University of Arkansas RFID Research Center news (2008), RFID improves inventory accuracy", "2008", "https://news.uark.edu/articles/11238/rfid-improves-inventory-accuracy-university-of-arkansas-study-finds", "Origin of the widely repeated '65% to 95%' accuracy figure (with Hardgrave's talks); Macy's and Zara figures are company statements", "ANEC", "not recorded", "provenance of a repeated number", "0.2 kept (0.25 at stores); shrink 0.8 (was 0.5)", HELP),
 ("ml_forecast", "effect size", "forecast_skill", "Spiliotis, Makridakis, Semenoglou & Assimakopoulos (2022), Comparison of statistical and ML methods for daily SKU demand forecasting, Operational Research 22:3037-3061", "2022", "https://link.springer.com/article/10.1007/s12351-020-00605-2", "Global ML methods beat statistical benchmarks on daily SKU data; gains concentrated on fast movers, small for intermittent SKUs", "PR", "snippet/abstract", "context (supports the store-level LOW)", "0.3 at DC/MFG, 0.1 at stores (was 0.3 everywhere)", HELP),
 ("ml_forecast", "effect size", "forecast_skill", "Walmart AI forecasting claims (third-party case write-ups, e.g. TSG Strategy)", "", "https://www.tsgstrategy.com/assets/casestudies/casestudy_walmart.pdf", "Store-SKU weekly error ~30% to 15-20%; holiday in-stock 92% to 98% (third-party estimates)", "ANEC (unverified)", "snippet/abstract", "HIGH anchor (weak)", "0.3 at DC/MFG, 0.1 at stores (was 0.3 everywhere)", HELP),
 ("control_tower", "effect size", "visibility", "Goncalves & Moshtari (2021), The impact of information visibility on ordering dynamics, System Dynamics Review 37:126-154", "2021", "https://onlinelibrary.wiley.com/doi/full/10.1002/sdr.1687", "Visibility makes subjects react less aggressively to own inventory gaps and weight the supply line more; effect larger upstream", "PR", "snippet/abstract", "context (larger upstream)", "0.6 (was 1.0); LOW 0.25-0.35, HIGH 0.85-0.95", HELP),
 ("control_tower", "effect size", "visibility", "Sears/Michelin and Wegmans/Nabisco VICS CPFR pilots (Supermarket News and secondary summaries)", "", "https://www.supermarketnews.com/archive/scoping-out-cpfr", "Sears/Michelin: inventory -25%, in-stock +4.3%; Wegmans/Nabisco: inventory -17.7%, store service 93% to 97%", "ANEC", "snippet/abstract", "HIGH-side context (pilots)", "0.6 (was 1.0); LOW 0.25-0.35, HIGH 0.85-0.95", HELP),
 ("aps", "effect size", "capacity_mult", "Siemens Opcenter blog, Proform; ATS/Koch Foods case study", "", "https://blogs.sw.siemens.com/opcenter/proform-manages-diverse-scheduling-demands-to-boost-efficiency-by-87/ ; https://lean-scheduling.com/case-studies/koch-foods-opcenter-production-planning-scheduling-case-study/", "Proform '+87% efficiency' (metric undefined; unusable); Koch Foods runs plants at 95-100% of capacity after Opcenter", "VND / ANEC", "not recorded", "rejected as unusable", "+0.08 kept; LOW +0.03, HIGH +0.15", HELP),
 ("risk_intel", "effect size", "recovery_weeks_saved", "Resilinc COVID supplier survey via Retail Dive (2021)", "2021", "https://www.retaildive.com/news/snow-severe-weather-suppliers-manufacturing-disruption-resilinc/617056", "Suppliers disrupted an average of 3.3 weeks at that point (April 2020)", "VND", "not recorded", "context (outage length)", "min(2 weeks, 25% of outage); warning 0.3; lead 2 weeks", HELP),
 # ---- helper-reported sources that did not reach a write-up: implementation failure ----
 ("blockchain", "implementation failure", "p_fail", "Deloitte Global Blockchain Survey 2019/2020", "2020", "https://www.prnewswire.com/news-releases/deloittes-2020-global-blockchain-survey-nearly-40-of-respondents-have-blockchain-in-production-affirming-blockchains-maturity-as-a-true-strategic-priority-301077732.html", "23% (2019) to 39% (2020) of respondents have blockchain in production; n=1,488 executives at firms already engaged with blockchain (selection bias; per firm, not supply chain)", "IND", "page or full text", "upper bound on success", "P(fail) 0.65 / partial 0.25 @ 0.3-0.5 / full 0.10; platform death 0.4-0.6 over 5 yrs", HELP),
 ("blockchain", "implementation failure", "p_fail", "CAICT (He Baohong), speech reported by China Money Network (2018)", "2018", "https://www.chinamoneynetwork.com/2018/05/28/chinese-official-says-blockchain-projects-globally-had-average-life-span-of-1-22-years", "8% of 80,000+ projects alive; mean lifespan 1.22 years. Almost certainly the same GitHub data as Deloitte 2017: not an independent source", "IND", "snippet/abstract", "duplicate of Deloitte GitHub; do not double count", "P(fail) 0.65 / partial 0.25 @ 0.3-0.5 / full 0.10; platform death 0.4-0.6 over 5 yrs", HELP),
 ("blockchain", "implementation failure", "platform death", "S&P Global Market Intelligence (2022), Trade finance industry remains hopeful on blockchain despite failed projects (we.trade)", "2022", "https://www.spglobal.com/market-intelligence/en/news-insights/articles/2022/10/trade-finance-industry-remains-hopeful-on-blockchain-despite-failed-projects-72557910", "we.trade (12 banks + IBM) founded 2017-18, insolvent June 2022 (~4 years)", "ANEC", "snippet/abstract", "platform-death hazard", "P(fail) 0.65 / partial 0.25 @ 0.3-0.5 / full 0.10; platform death 0.4-0.6 over 5 yrs", HELP),
 ("rfid", "implementation failure", "p_fail", "Auburn RFID Lab, JCPenney RFID initiative white paper; Hardgrave, Key considerations for RFID pilots and deployments", "", "https://rfid.auburn.edu/papers/documents/KeyConsiderationsRFIDPilotsDeployments.pdf", "Apparel pilots lift accuracy ~65% to 95%+; pilots that never scale are discussed without counts", "PR-adjacent (sponsored)", "not recorded", "context", "P(fail) 0.20 / partial 0.40 @ 0.5-0.7 / full 0.40", HELP),
 ("rfid", "implementation failure", "p_partial (mandated followers)", "A tough pill to swallow? The lessons learned from mandatory RFID adoption (2023), Int. J. Production Economics", "2023", "https://www.sciencedirect.com/science/article/abs/pii/S0925527323000439", "Mandated suppliers often see little benefit of their own. Title only (403): retrieve through the ASU library", "PR", "title only", "to read: mandated-follower pattern", "mandated supplier: ~0.25 discontinue; 0.60 comply minimally @ 0.1-0.3 of own benefit", HELP),
 ("rfid", "implementation failure", "p_partial", "Shin & Eksioglu (2015), An empirical study of RFID productivity in the U.S. retail supply chain, IJPE", "2015", "https://www.sciencedirect.com/science/article/abs/pii/S092552731500050X", "Firm-level productivity effects of RFID. Title only, not read", "PR", "title only", "to read", "P(fail) 0.20 / partial 0.40 @ 0.5-0.7 / full 0.40", HELP),
 ("wh_robotics", "implementation failure", "p_fail", "MHI/Deloitte Annual Industry Report 2025; Peerless Research automation survey via Modern Materials Handling", "2025", "https://www.mmh.com/article/2025_industry_outlook_survey_warehouse_automation_comes_into_full_focus", "Barriers: budget 41%, cost/ROI 40% (Peerless); hiring 52% and talent 45% 'extremely challenging' (MHI). Barriers to adopting, not outcomes", "IND", "snippet/abstract", "context (SMEs mostly do not adopt)", "P(fail) 0.15 / partial 0.55 @ 0.5-0.7 / full 0.30", HELP),
 ("wh_robotics", "implementation failure", "p_fail", "Interact Analysis, Complexity not cost is the barrier to automation", "", "https://interactanalysis.com/insight/complexity-not-cost-barrier-to-automation/", "Complexity is the leading barrier; project orders fell 3% in 2024", "IND", "not recorded", "context", "P(fail) 0.15 / partial 0.55 @ 0.5-0.7 / full 0.30", HELP),
 ("wh_robotics", "implementation failure", "catastrophic loss", "Ocado warehouse fires: Andover (Feb 2019), Erith (Jul 2021)", "2019", "", "Andover site destroyed (~GBP100M+); Erith fire from a robot collision. Rare catastrophic-loss events", "ANEC (from memory, unverified)", "memory", "tail risk (not modelled)", "P(fail) 0.15 / partial 0.55 @ 0.5-0.7 / full 0.30", HELP),
 ("routing", "implementation failure", "p_fail; p_partial", "ARC Advisory Group TMS market study via Logistics Management", "", "https://www.logisticsmgmt.com/article/supply_chain_and_logistics_technology_8_trends_driving_tms_adoption", "63% of users say freight costs would rise 5%+ without their TMS; 23% say 10%+. Survivors only: shows benefit of successes, not the failure rate", "IND", "not recorded", "context (survivor bias)", "P(fail) 0.15 / partial 0.50 @ 0.5-0.7 / full 0.35 (borrowed)", FE),
 ("routing", "implementation failure", "p_partial", "Waste360, challenges can prohibit routing software adoption; Kardinal, the paradox of route optimization", "", "https://www.waste360.com/route-optimization/challenges-can-prohibit-routing-software-adoption-despite-innovations ; https://kardinal.ai/the-paradox-of-route-optimization-when-theory-collides-with-real-world-operations/", "Drivers and dispatchers override planned routes; software goes unused after go-live. No percentages", "VND / ANEC", "not recorded", "partial-success mechanism (shelfware)", "P(fail) 0.15 / partial 0.50 @ 0.5-0.7 / full 0.35 (borrowed)", FE),
 ("routing", "implementation failure", "p_fail", "Panorama Consulting, Top reasons for TMS failure", "", "https://www.panorama-consulting.com/top-reasons-for-tms-failure/", "Qualitative causes only", "VND", "not recorded", "context", "P(fail) 0.15 / partial 0.50 @ 0.5-0.7 / full 0.35 (borrowed)", HELP),
 ("all", "implementation failure", "p_partial", "PwC (2025), Digital Trends in Operations Survey", "2025", "https://www.pwc.com/us/en/services/consulting/supply-chain-operations/digital-supply-chain-survey.html", "92% cite at least one reason supply chain tech investments have not fully delivered; integration complexity 47%, data issues 44%. Often misread as '92% failed'", "IND", "not recorded", "general prior (full success is rare); causes for the small-firm scaling", "general priors: BCG 30/44/26; Standish 31/50/19; 56% less value; fat-tailed overruns", HELP),
 ("ml_forecast", "implementation failure", "p_fail", "MIT SMR / BCG (2019), Winning with AI", "2019", "https://sloanreview.mit.edu/projects/winning-with-ai/", "7 in 10 report minimal or no impact from AI; fewer than 2 in 5 of those investing report gains (~2,500 executives)", "IND", "not recorded", "context", "P(fail) 0.45 / partial 0.35 @ 0.5 / full 0.20", HELP),
 ("all", "implementation failure", "p_partial", "Gartner (May 2025), 60% of supply chain digital adoption efforts will fail to deliver promised value by 2028", "2025", "https://www.gartner.com/en/newsroom/press-releases/2025-05-07-gartner-predicts-60-percent-of-supply-chain-digital-adoption-efforts-will-fail-to-deliver-promised-value-by-2028", "A prediction (n=579 practitioners surveyed), not a measurement", "IND (forecast)", "page or full text", "context; do not use as a rate", "general priors: BCG 30/44/26; Standish 31/50/19; 56% less value; fat-tailed overruns", HELP),
 ("ml_forecast", "implementation failure", "p_fail", "Gartner (June 2025), just 23% of supply chain organizations have a formal AI strategy", "2025", "https://www.gartner.com/en/newsroom/2025-06-11-gartner-survey-shows-just-23-percent-of-supply-chain-organizations-have-a-formal-ai-strategy", "23% have a formal AI strategy; a related survey finds 55% of supply chain chiefs unclear on AI returns", "IND", "snippet/abstract", "context (maturity)", "P(fail) 0.45 / partial 0.35 @ 0.5 / full 0.20", HELP),
 ("ml_forecast", "implementation failure", "p_partial", "Fildes et al. (2024/25), Forecast value added in demand planning, IJF (citing Fildes & Goodwin 2007; Fildes & Petropoulos 2015)", "2024", "https://www.sciencedirect.com/science/article/pii/S0169207024000736", "On average ~37%+ of statistical forecasts are judgmentally adjusted; field studies up to 90%", "PR", "snippet/abstract", "partial-success mechanism (overrides)", "P(fail) 0.45 / partial 0.35 @ 0.5 / full 0.20", HELP),
 ("aps", "implementation failure", "p_partial", "Jonsson, Kjellsdotter & Rudberg (2007), Applying APS for supply chain planning: three case studies, IJPDLM", "2007", "https://publications.lib.chalmers.se/records/fulltext/66897/local_66897.pdf", "Three cases of APS in practice; problems of use after go-live", "PR (cases)", "not recorded", "context", "P(fail) 0.15 / partial 0.50 @ 0.45 / full 0.35", HELP),
 ("aps", "implementation failure", "p_partial", "Zoryk-Schalla, Fransoo & de Kok (2004), Modeling the planning process in advanced planning systems, Information & Management", "2004", "https://www.sciencedirect.com/science/article/abs/pii/S0378720604000072", "Hierarchical planning is very hard to capture in APS; models reworked during implementation (single case)", "PR", "snippet/abstract", "context", "P(fail) 0.15 / partial 0.50 @ 0.45 / full 0.35", HELP),
 ("aps", "implementation failure", "p_fail; p_partial", "Panorama Consulting ERP reports (archive; 2023 n=183)", "2023", "https://www.panorama-consulting.com/resource-center/erp-report-archives/", "81% realised some benefits; of those 41% under half the expected benefits; 16% no measurable benefit (ERP proxy for APS)", "IND (self-selected)", "snippet/abstract", "MID support (16% no benefit)", "P(fail) 0.15 / partial 0.50 @ 0.45 / full 0.35", HELP),
 ("risk_intel", "implementation failure", "p_partial", "BCI Supply Chain Resilience Reports 2023 and 2024", "2024", "https://www.thebci.org/resource/bci-supply-chain-resilience-report-2024.html", "Share analysing critical suppliers to tier 4+ rose 3.7% to 17.1%; 24.1% had tier-2 disruptions; the 'map but don't use' share is gated", "IND", "snippet/abstract", "context", "P(fail) 0.30 / partial 0.45 @ 0.35 / full 0.25", HELP),
 ("risk_intel", "implementation failure", "p_partial", "IT-operations alert-fatigue vendor survey (2026), as an analogue", "2026", "", "57% say fewer than 30% of alerts are actionable; 83% ignore alerts at least occasionally. No supply-chain-specific data exists", "VND", "snippet/abstract", "analogue only", "P(fail) 0.30 / partial 0.45 @ 0.35 / full 0.25", HELP),
 ("control_tower", "implementation failure", "p_partial", "McKinsey supply chain pulse surveys 2021-2025 (tier visibility)", "2024", "https://www.mckinsey.com/capabilities/operations/our-insights/supply-chain-risk-survey-2024", "Tier-1 visibility ~95%; tier-2+ ~42% and falling in 2023-24; only 2% had tier-3+ visibility in 2021: multi-party visibility decays", "IND", "snippet/abstract", "multi-party scaling (coverage decays)", "P(fail) 0.25 / partial 0.50 @ 0.4 / full 0.25", HELP),
 ("control_tower", "implementation failure", "p_partial", "Supermarket News (2003), Sizing up CPFR; Industry Directions survey (n=130)", "2003", "https://www.supermarketnews.com/independents-regional-grocers/sizing-up-cpfr", "Only 6% listed CPFR as a high IT priority; 68% piloting, researching, or preparing", "IND", "snippet/abstract", "multi-party scaling (pilots rarely scale)", "P(fail) 0.25 / partial 0.50 @ 0.4 / full 0.25", HELP),
 ("risk_intel", "effect size", "recovery_weeks_saved", "Resilinc EventWatch 2021 press release", "2021", "https://resilinc.ai/press-release/supply-chain-disruptions-up-88-in-2021-with-factory-fires-taking-top-spot-contributing-to-record-breaking-supply-shortages/", "11,642 alerts; fires 1,946 (17%); 60% of alerts triggered WarRooms; 90% of events 'human-caused'", "VND", "not recorded", "warning-share context", "min(2 weeks, 25% of outage); warning 0.3; lead 2 weeks", RI),
]


def main() -> None:
    with CSV.open() as f:
        existing = list(csv.DictReader(f))
    fields = list(existing[0].keys())
    n = len(existing)
    assert not any(r["date_added"] == "2026-09-19b" for r in existing), "already appended"
    new = []
    for i, row in enumerate(ROWS, n + 1):
        tech, topic, param, cit, year, url, finding, flag, read, role, informs, src = row
        new.append(dict(zip(fields, [f"C{i:03d}", "2026-09-19b", tech, topic, param, cit, year, url, finding, flag,
                                     read, role, informs, src])))
    with CSV.open("a", newline="") as f:
        csv.DictWriter(f, fieldnames=fields).writerows(new)
    print(len(new), "rows appended; log now has", n + len(new))


if __name__ == "__main__":
    main()
